"""Added gif table

Revision ID: 202f848131fe
Revises: d1a0c96c825e
Create Date: 2019-03-03 20:23:04.983900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202f848131fe'
down_revision = 'd1a0c96c825e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gif_timestamp'), 'gif', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gif_timestamp'), table_name='gif')
    op.drop_table('gif')
    # ### end Alembic commands ###
