"""

Revision ID: 5b98274e6608
Revises: b17d9fbfe3fc
Create Date: 2019-03-12 10:53:22.448607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b98274e6608'
down_revision = 'b17d9fbfe3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('plat_id', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('ubi_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_plat_id'), 'user', ['plat_id'], unique=True)
    op.create_index(op.f('ix_user_ubi_id'), 'user', ['ubi_id'], unique=False)
    op.drop_index('ix_user_r6_user', table_name='user')
    op.create_index(op.f('ix_user_r6_user'), 'user', ['r6_user'], unique=False)
    op.drop_index('ix_user_uplay_id', table_name='user')
    op.drop_column('user', 'uplay_id')
    op.drop_column('user', 'user_platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_platform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('uplay_id', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_uplay_id', 'user', ['uplay_id'], unique=True)
    op.drop_index(op.f('ix_user_r6_user'), table_name='user')
    op.create_index('ix_user_r6_user', 'user', ['r6_user'], unique=True)
    op.drop_index(op.f('ix_user_ubi_id'), table_name='user')
    op.drop_index(op.f('ix_user_plat_id'), table_name='user')
    op.drop_column('user', 'ubi_id')
    op.drop_column('user', 'plat_id')
    # ### end Alembic commands ###
