"""Added platform table

Revision ID: b17d9fbfe3fc
Revises: d8f9e32fe26a
Create Date: 2019-03-05 15:53:08.432440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17d9fbfe3fc'
down_revision = 'd8f9e32fe26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'platform', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'platform_id')
    op.drop_table('platform')
    # ### end Alembic commands ###
