"""fresh init

Revision ID: bc45904db47c
Revises: 
Create Date: 2019-03-02 12:45:01.458742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc45904db47c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_name', sa.String(length=128), nullable=True),
    sa.Column('clan_avatar', sa.String(length=128), nullable=True),
    sa.Column('clan_admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_clan_admin'), 'clan', ['clan_admin'], unique=True)
    op.create_index(op.f('ix_clan_clan_name'), 'clan', ['clan_name'], unique=True)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1600), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r6_user', sa.String(length=64), nullable=True),
    sa.Column('uplay_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=94), nullable=True),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('twitch', sa.String(length=80), nullable=True),
    sa.Column('youtube', sa.String(length=80), nullable=True),
    sa.Column('mixer', sa.String(length=80), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mixer'),
    sa.UniqueConstraint('twitch'),
    sa.UniqueConstraint('youtube')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_r6_user'), 'user', ['r6_user'], unique=True)
    op.create_index(op.f('ix_user_uplay_id'), 'user', ['uplay_id'], unique=True)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('kd_ratio', sa.Float(asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('wl_ratio', sa.Float(asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('waifu', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('kd_ratio', sa.Float(asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('wl_ratio', sa.Float(asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly')
    op.drop_table('diff')
    op.drop_table('data')
    op.drop_index(op.f('ix_user_uplay_id'), table_name='user')
    op.drop_index(op.f('ix_user_r6_user'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('ticket')
    op.drop_table('region')
    op.drop_index(op.f('ix_clan_clan_name'), table_name='clan')
    op.drop_index(op.f('ix_clan_clan_admin'), table_name='clan')
    op.drop_table('clan')
    # ### end Alembic commands ###
