"""Drop table test

Revision ID: d1a0c96c825e
Revises: 07e23f7e73f7
Create Date: 2019-03-03 18:10:45.243438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1a0c96c825e'
down_revision = '07e23f7e73f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'drop_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('drop_test', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
